# Generated by Django 4.0.4 on 2022-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkinda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='firmaOzellikleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmaOzellik_title', models.CharField(blank=True, max_length=50)),
                ('firmaOzellik_text', models.TextField(blank=True)),
                ('firmaOzellik_icon', models.ImageField(blank=True, upload_to='media/firmaOzellikleriIcons/%Y/%m/%d/')),
                ('firmaOzellik_adet', models.IntegerField(blank=True)),
                ('firmaOzellik_created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
