# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_surname', models.CharField(blank=True, max_length=50)),
                ('user_password', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(blank=True, max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=50)),
                ('user_phone', models.CharField(blank=True, max_length=12)),
                ('about_user', models.TextField(blank=True)),
                ('user_image', models.ImageField(blank=True, upload_to='media/userProfile/%Y/%m/%d')),
                ('user_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
