# Generated by Django 4.0.4 on 2022-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformations',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='userProfile/%Y/%m/%d'),
        ),
    ]
