# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sektorler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor_adi', models.CharField(blank=True, max_length=50)),
                ('sektor_text', models.TextField(blank=True)),
                ('sektor_img', models.ImageField(blank=True, default='media/sektorlerDefault/avrupa ofıs kale.jpg', upload_to='media/sektorler/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
