# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='firmaBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(blank=True, max_length=50)),
                ('firma_kurulus_tarihi', models.DateTimeField(blank=True)),
                ('firma_logo', models.ImageField(blank=True, default='media/firmaLogoDefault/logo-corpus.svg', upload_to='media/firmaBilgi/%Y/%m/%d')),
                ('firma_email', models.EmailField(blank=True, max_length=254)),
                ('firma_telefon', models.CharField(blank=True, max_length=18)),
                ('firma_lokasyon', models.CharField(blank=True, max_length=500)),
                ('firma_created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
