# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=50)),
                ('post_tag', models.CharField(blank=True, max_length=50)),
                ('post_text', models.TextField(blank=True)),
                ('post_image', models.ImageField(blank=True, upload_to='media/postsImages/%Y/%m/%d')),
                ('post_published_date', models.DateTimeField(auto_now_add=True)),
                ('post_created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
