# Generated by Django 4.0.4 on 2022-05-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeinformations_user_image'),
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vlog',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='postsImages/%Y/%m/%d'),
        ),
    ]
