# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_tag', models.CharField(blank=True, max_length=50)),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('page_img', models.ImageField(blank=True, default='media/pageDefault/paper-2.jpg', upload_to='media/pageImage/%Y/%m/%d/')),
                ('available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
