# Generated by Django 4.0.4 on 2022-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalismaAlanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_created_date', models.DateTimeField(auto_created=True)),
                ('calisma_icon', models.ImageField(blank=True, default='media/calismaAlanlariDefault/img.png', upload_to='media/calismaIcon/')),
                ('calisma_title', models.CharField(blank=True, max_length=50)),
                ('calisma_metni', models.TextField(blank=True)),
                ('calisma_published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
